<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <!-- 包含各个平台的发布文件 -->
    <ItemGroup>
        <None Include="**\*.*" CopyToOutputDirectory="Never"/>
    </ItemGroup>

</Project>
